graph TD
    %% --- External Network ---
    UserApp1[User request for<br>Foo.bar/app1] --> Core[Core Network Fabric]
    UserApp2[User request for<br>Foo.bar/app2] --> Core
    Core --> TOR1[TOR]
    Core --> TOR2[TOR]

    %% --- OCP CLUSTER 1 ---
    subgraph OCP CLUSTER 1
        subgraph LB-Ingress-1 [ ]
            direction LR
            LB1[Metal LB]
            Ingress1(Ingress Route)
            LB1 --> Ingress1
        end
        
        SvcApp1[Service for /app1]
        mTLS_1_1[mTLS Router]
        mTLS_2_1[mTLS Router]

        Ingress1 -- Path based selection<br>for Foo.bar/app1 --> SvcApp1
        Ingress1 -- Path based selection<br>for Foo.bar/app2 --> mTLS_1_1
        
        SvcApp1 -- Path based selection<br>for Foo.bar/app1 --> mTLS_2_1
        
        mTLS_1_1 -- Service Network for /app2 --> mTLS_2_1
        mTLS_2_1 -- Service Network for /app1 --> mTLS_1_1
    end

    %% --- OCP CLUSTER 2 ---
    subgraph OCP CLUSTER 2
        subgraph LB-Ingress-2 [ ]
            direction LR
            LB2[Metal LB]
            Ingress2(Ingress Route)
            LB2 --> Ingress2
        end

        SvcApp2[Service for /app2]
        mTLS_1_2[mTLS Router]
        mTLS_2_2[mTLS Router]

        Ingress2 -- Path based selection<br>for Foo.bar/app1 --> mTLS_1_2
        Ingress2 -- Path based selection<br>for Foo.bar/app2 --> SvcApp2
        
        SvcApp2 -- Path based selection<br>for Foo.bar/app2 --> mTLS_2_2
        
        mTLS_1_2 -- Service Network for /app1 --> mTLS_2_2
        mTLS_2_2 -- Service Network for /app2 --> mTLS_1_2
    end
    
    %% --- BGP & Cross-Cluster ---
    TOR1 -- BGP Advertisment<br>(192.168.155.151/32) --> LB1
    TOR2 -- BGP Advertisment<br>(192.168.155.151/32) --> LB2

    mTLS_1_1 -. Encrypted Transport .- mTLS_1_2
    mTLS_2_1 -. Encrypted Transport .- mTLS_2_2
